// Generated by Selenium IDE
const { Builder, By, Key, until } = require('selenium-webdriver')
const assert = require('assert')
const { sleep, takeScreenShot, findElement } = require('../helper')

describe('login', function() {
  this.timeout(120000)
  let driver
  let vars
  beforeEach(async function() {
    driver = await new Builder().forBrowser('chrome').build()
    vars = {}
  })
  afterEach(async function() {
    await driver.quit();
  })
  it('login', async function() {
    await driver.get("http://54.254.149.126:4301/login")
    await driver.manage().window().setRect({ width: 1052, height: 808 })
    await takeScreenShot('./images', driver)
    const userName = await driver.findElement(By.css("input[type='text'][placeholder='Username']"))
    userName.sendKeys("hoangdv@nec.vn")

    const password = await driver.findElement(By.css("input[type='password'][placeholder='Password']"))
    password.sendKeys("Necvn@123");

    await takeScreenShot('./images', driver)
    const loginBtn = await driver.findElement(By.xpath("//button[contains(.,\'Login\')]"))
    loginBtn.click();
    
    await sleep(20000)
    await takeScreenShot('./images', driver)
    await findElement(driver, By.xpath("xpath=//h1[contains(.,'CAMERA MANAGEMENT')]"), 1000);
  })
})
