// Generated by Selenium IDE
const {
  Builder,
  By,
  Key,
  until
} = require('selenium-webdriver')
const { takeScreenShot, sleep } = require('../helper');
const config = require('../config/google_search_config.json');

describe('search', function () {
  this.timeout(30000)
  let driver
  let vars
  beforeEach(async function () {
    driver = await new Builder().forBrowser('chrome').build()
    vars = {}
  })
  afterEach(async function () {
    await driver.quit();
  })
  it('search', async function () {
    await driver.get("https://www.google.com/")
    await driver.manage().window().setRect({
      width: 1032,
      height: 634
    })
    await takeScreenShot(config.name, driver)
  
    const searchBox = await driver.findElement(By.name("q"))
    searchBox.sendKeys("gss-sol", Key.ENTER)
    await takeScreenShot(config.name, driver)
    await sleep(1000);

    await takeScreenShot(config.name, driver)

  })
})