// Generated by Selenium IDE
const { Builder, By, Key, until } = require('selenium-webdriver')
const assert = require('assert')

describe('search', function() {
  this.timeout(30000)
  let driver
  let vars
  beforeEach(async function() {
    driver = await new Builder().forBrowser('chrome').build()
    vars = {}
  })
  afterEach(async function() {
    await driver.quit();
  })
  it('search', async function() {
    // Test name: search
    // Step # | name | target | value
    // 1 | open | / | 
    // open URL
    await driver.get("https://www.google.com/")
    // 2 | setWindowSize | 1032x634 | 
    await driver.manage().window().setRect({ width: 1032, height: 634 })
    // 3 | type | name=q | gss-sol
    await driver.findElement(By.name("q")).sendKeys("gss-sol")
    // // 4 | click | name=btnK | 
    // await driver.findElement(By.name("btnK")).click()
    // // 5 | click | xpath=//h3[contains(.,'Công Ty Cổ Phần Giải Pháp Không Gian Xanh')] | 
    // await driver.findElement(By.xpath("//h3[contains(.,\'Công Ty Cổ Phần Giải Pháp Không Gian Xanh\')]")).click()
    // // 6 | assertElementPresent | xpath=//div[@class='footer_bottom' and contains(., "Green Space Solution")]  | 
    // // confirm the GSS website is opened
    // {
    //   const elements = await driver.findElements(By.xpath("//div[@class=\'footer_bottom\' and contains(., \"Green Space Solution\")] "))
    //   assert(elements.length)
    // }
  })
})
