// Generated by Selenium IDE
const { Builder, By, Key, until } = require('selenium-webdriver')
const assert = require('assert')
const fs = require('fs');
const { v4: uuidv4 } = require('uuid');
var config = require('config.json')('./config/search.json');

const sleep = async (ms) => {
  return new Promise(resolve => setTimeout(resolve, ms));
}

describe('search', function() {
  this.timeout(30000)
  let driver
  let vars
  beforeEach(async function() {
    driver = await new Builder().forBrowser('chrome').build()
    vars = {}
  })
  afterEach(async function() {
    await driver.quit();
  })
  it('search', async function() {
    // Test name: search
    // Step # | name | target | value
    // 1 | open | / | 
    // open URL
    await driver.get(config.url)
    // 2 | setWindowSize | 1032x634 | 
    await driver.manage().window().setRect({ width: 1032, height: 634 })
    // 3 | type | name=q | gss-sol
    await driver.findElement(By.name("q")).sendKeys("gss-sol")
    const encodedString = await driver.takeScreenshot();
    await fs.writeFileSync('./images/' + uuidv4() + '.png', encodedString, 'base64');
    await driver.findElement(By.name("q")).sendKeys(Key.ENTER)

    await sleep(3000);
  })
})
