// Generated by Selenium IDE
const { Builder, By, Key, until } = require('selenium-webdriver')
const assert = require('assert')

describe('login git hub', function() {
  this.timeout(30000)
  let driver
  let vars
  beforeEach(async function() {
    driver = await new Builder().forBrowser('chrome').build()
    vars = {}
  })
  afterEach(async function() {
    await driver.quit();
  })
  it('login git hub', async function() {
    await driver.get("https://github.com/")
    await driver.manage().window().setRect({ width: 1936, height: 1056 })
    await driver.findElement(By.linkText("Sign in")).click()
    await driver.findElement(By.id("login_field")).click()
    await driver.findElement(By.id("login_field")).sendKeys("jinseimelody@gmail.com")
    await driver.findElement(By.id("password")).click()
    await driver.findElement(By.id("password")).sendKeys("_Jin.Melody97")
    await driver.findElement(By.name("commit")).click();
  })
})
